### ISSUE TITLE
Undefined class Future in lib/src/runner.dart

### ISSUE THREAD

**Issue by pschiffmann** [dart-lang/mono_repo#109]
The file is missing the `import 'dart:async';` directive.

This means that `pub global activate mono_repo` currently exits with
```
Failed to precompile mono_repo:mono_repo:
file:///Users/philippschiffmann/.pub-cache/hosted/pub.dartlang.org/mono_repo-1.2.0/lib/src/runner.dart:36:3: Error: 'Future' expects 0 type arguments.
  Future<Null> runCommand(ArgResults topLevelResults) async {
  ^
file:///Users/philippschiffmann/.pub-cache/hosted/pub.dartlang.org/mono_repo-1.2.0/lib/src/runner.dart:36:16: Error: The return type of the method 'MonoRepoRunner::runCommand' is invalid-type, which does not match the return type of the overridden method (dart.async::Future<dart.core::Null>).
Change to a subtype of dart.async::Future<dart.core::Null>.
  Future<Null> runCommand(ArgResults topLevelResults) async {
               ^
```
on OS X with Dart Version 2.0.0.

**Comment by natebosch** [comment]
@kevmoo - need to add the import and publish a `+1`. Probably don't want to bump the SDK constraint until `2.1.0` stable.

This happened because the SDK opened a very easy hole to fall in to allowing you to omit the import on newer SDKs and we typically work with dev versions locally.

**Comment by kevmoo** [comment]
I have a fix coming, @pschiffmann – excited you're using this package!

**Comment by kevmoo** [comment]
Thanks for the report, @pschiffmann – run `pub global activate mono_repo` again and you should be good to go!

**Comment by pschiffmann** [comment]
> This happened because the SDK opened a very easy hole to fall in to allowing you to omit the import on newer SDKs and we typically work with dev versions locally.

Now I'm a bit confused. I'm currently looking into Travis CI explicitly because it lets me validate that I don't accidentally violate my packages SDK constraints. The `dartanalyzer` task catches bugs like this one if you add `stable` as a language version to your mono_pkg.yaml, right?

**Comment by kevmoo** [comment]
>  if you add stable as a language version to your mono_pkg.yaml, right?

Right!

**Comment by natebosch** [comment]
> The `dartanalyzer` task catches bugs like this one if you add `stable` as a language version to your mono_pkg.yaml, right?

That's true for now. Once Dart 2.1.0 is released then adding `stable` _won't_ help catch this. In order to be safe you'd need to add the specific lower bound from your `pubspec.yaml` SDK constraints as one of the versions to run against in CI. `stable` is a moving target.

**Comment by kevmoo** [comment]
You can always add `2.0.0` – or whichever stable version you like – to be
specific about a shipped version. These are not a moving target.
