### ISSUE TITLE
mono_repo pub get cant resolve relative path packages

### ISSUE THREAD

**Issue by liuqipeng417** [dart-lang/mono_repo#152]
`mono_repo pub get` cant get relative path packages correctly.

![image](https://user-images.githubusercontent.com/11896359/56550618-b1a0bd00-65b8-11e9-9d70-e3c60eff3281.png)

**Comment by kevmoo** [comment]
Could you provide more details about the setup of your repo?

Where did you run `mono_repo`? How are your directories configured?

**Comment by liuqipeng417** [comment]
It's my mistake, just close this issue.

**Comment by kevmoo** [comment]
cool!
