### ISSUE TITLE
Clarify how to make travis.sh executable on Windows

### ISSUE THREAD

**Issue by jack-r-warren** [dart-lang/mono_repo#163]
Right now, when `mono_repo` makes the `travis.sh` file for the first time, it prints the following:
```text
Make sure to mark `./tool/travis.sh` as executable.
  chmod +x ./tool/travis.sh
```
That's perfectly helpful for anyone on a Linux/Mac, but on Windows the equivalent command is pretty obscure:
```powershell
git update-index --add --chmod=+x .\tool\travis.sh
```
From what I understand, Windows doesn't have the concept of executable permissions so git has to be told to emulate the effects of the Linux command.

I'm happy to make a PR to add a platform check to the message, but the cause for this issue is to check how I should go about testing that. Right now, almost every test fails when run on Windows simply because of path slashes being the other direction. I'm not very knowledgeable on platform-specific Dart testing, and especially so with how that would work with the automated tests. Is this something where not testing those few lines would be acceptable? Can the platform seen by `dart:io` be spoofed?

**Comment by kevmoo** [comment]
Great suggestion! PR welcome!
