### ISSUE TITLE
Fully support Windows on Travis

### ISSUE THREAD

**Issue by grouma** [dart-lang/mono_repo#170]

**Comment by jakemac53** [comment]
It looks like this is much easier than originally anticipated - all we really need to do is support generating all the required stages based on the `os` setting.

The generated shell scripts run as expected on travis windows.

**Comment by jakemac53** [comment]
We should also figure out how to deal with conditionally adding `.exe` or `.bat` where required, see https://github.com/dart-lang/webdev/pull/712/files#diff-b1de5166a13e970c48aaa8bfb6775ef8R5 for one hack around this for some general tools which might be enough to start at least.

**Comment by kevmoo** [comment]
I thought we'd just move to generating and running a Dart script and use it
in both places...

**Comment by jakemac53** [comment]
That was the original thought yes and I am fine with that but there is no reason to block windows support on that. It almost fully works already today.
