### ISSUE TITLE
Custom travis configuration

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/mono_repo#177]
To support additional Travis options like [apt packages](https://github.com/dart-lang/samples/pull/23/files#diff-354f30a63fb0907d4ad57269548329e3R7), users currently need to generate the .travis.yml file and remember to manually add additional configuration.

I'm not sure if it makes sense to add arbitrary config options to `mono_pkg.yaml` or to have a new file like `travis_options.yml` that this package can read from and add to the final `.travis.yml` file.

**Comment by kevmoo** [comment]
PRs welcome!

**Comment by johnpryan** [comment]
Oops, it turns out this is already supported. If you [set the `travis` field](https://github.com/dart-lang/samples/pull/28/commits/6b701b9187bd50497e5c0a01b8027e0febc99380) in `mono_repo.yaml` they are treated as custom travis options.
