### ISSUE TITLE
Version check: Ensure compatible version ranges

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/mono_repo#28]
... across different sub-packages. No use if pkg_a uses `0.1.0` and pkg_b uses `0.2.0`.

**Comment by matanlurey** [comment]
My understanding is [`VersionConstraint.allowsAny`](https://www.dartdocs.org/documentation/pub_semver/1.3.2/pub_semver/VersionConstraint/allowsAny.html) should handle this for me.

**Comment by matanlurey** [comment]
Some Qs:

* Should this be opt-in, opt-out, or just always on?
* If opt-, is this a flag per `mono_repo.yaml` file?
* Do we care about `dev_dependencies`?

/cc @alorenzen @natebosch

**Comment by natebosch** [comment]
I don't think we need to check the full cross product.

For a concrete example both `_bazel_codegen` and `build` need to be compatible, and both `build_runner` and `build` need to be compatible, but `build_runner` and `_bazel_codegen` don't necessarily need to be compatible.

Maybe something like "If pkg_a depends on pkg_b within the same repo they need to have compatible constraints for all deps"

**Comment by matanlurey** [comment]
I guess the other option is no magic, and have the configuration say:

```yaml
check_version_constraints:
  "build":
    - "bazel_codegen"
    - "build_runner"
```

WDUT?

**Comment by natebosch** [comment]
Would prefer some magic over no magic if we can find some heuristics that work well enough - otherwise it's another bit of config that changes rarely but could go stale.

**Comment by matanlurey** [comment]
I no longer need this.
