### ISSUE TITLE
Better to log when a before script is called – instead of adding noise in the common case

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/mono_repo#39]
https://github.com/dart-lang/mono_repo/blob/837ced4525b63c4ce12314458fb0c52db5759632/mono_repo/lib/src/commands/travis.dart#L238

CC @alorenzen

**Comment by alorenzen** [comment]
I was mostly just copying the pattern from the tasks section. Happy to change it if you prefer.

**Comment by kevmoo** [comment]
Since it's an exception, I think it'd be good to print when we run it.

...now folks will see a print out w/ out context
