### ISSUE TITLE
generated `tool/travis.sh` is using a weird encoding

### ISSUE THREAD

**Issue by alorenzen** [dart-lang/mono_repo#43]
The generated shell script `tool/travis.sh` from the travis command is using a weird encoding causing some of our tools to treat it as binary instead of text.

**Comment by kevmoo** [comment]
On it!

**Comment by alorenzen** [comment]
The issue is related to the ansi wrappring. If I remove those bits manually, then everything seems to work fine.

**Comment by kevmoo** [comment]
Published in 0.2.1 - https://pub.dartlang.org/packages/mono_repo
