### ISSUE TITLE
Inconsistent file naming

### ISSUE THREAD

**Issue by natebosch** [dart-lang/mono_repo#54]
The top level config is [`mono_repo.yaml`](https://github.com/dart-lang/mono_repo/blob/b3c83b68f5676acd411a7b390d523fed6ed0d1e5/mono_repo/lib/src/utils.dart#L15)

The per-package config is [`.mono_repo.yml`](https://github.com/dart-lang/mono_repo/blob/b3c83b68f5676acd411a7b390d523fed6ed0d1e5/mono_repo/lib/src/mono_config.dart#L12)

These are inconsistent with their usage of a leading `.` and with the file extension. Can we align them?

**Comment by kevmoo** [comment]
We fixed all this up...a while ago.
